### ISSUE TITLE
Ночівля

### ISSUE THREAD

**Issue by MyroslavaStopets** [mskab/Weekend#1]
1) умови проживання, вартість
2) можливі варіанти - альтернативні або запасні

**Comment by MyroslavaStopets** [comment]
Яке місце призначення? 
Для того щоб обрати місце ночівлі необхідно знати місце подорожі

**Comment by MyroslavaStopets** [comment]
Потрібна ваша допомога. Який варіант проживання буде найкомфортнішим? 
1) котедж
2) одномісні номери у готелі
3) апартаменти

**Comment by mskab** [comment]
На мій погляд, краще котедж.

**Comment by Severyn-Yanchynskyj** [comment]
Одобрюю
