### ISSUE TITLE
Харчування

### ISSUE THREAD

**Issue by mskab** [mskab/Weekend#5]
1. в дорозі
2. на місці

**Comment by mskab** [comment]
Пропоную визначитись з типом харчування. В нас є декілька варіантів. Ми можемо харчуватись виключно в закладах громадського харчування, самостійно готувати або поєднувати попередні два варіанти.  Що вам більше до вподоби?

**Comment by Severyn-Yanchynskyj** [comment]
Поєднювати

**Comment by MyroslavaStopets** [comment]
Також вважаю, що найкраще буде поєднювати

**Comment by mskab** [comment]
Я добавила два файли 
1)Продукти в дорогу
2)Список продуктів для самостійного приготування
Можливо, у когось є якісь побажання? Повідомте і я охоче добавлю в список.
